### ISSUE TITLE
Feature Request: nixpkgs silver for us poors

### ISSUE THREAD

**Issue by djacu** [Jaculabilis/nixpkgs-gold#1]
Loving the premium vibes of nixpkgs gold—it truly shines! But for us working class peasants, could you introduce a "nixpkgs silver" tier? Something affordable and accessible for us humble mortals who can’t quite afford the dazzling exclusivity of gold.

vibes
![image](https://github.com/user-attachments/assets/25ebc89f-f05a-444e-ab7f-f8cc8b1f3135)

**Comment by Jaculabilis** [comment]
The original `stdenv` is already an affordable and accessible entry-level offering for building derivations, and many specialized use cases are served by alternative build environments like `stdenv_32bit` or `clangStdenv`. However, you make a good point that we could make nixpkgs gold :tm:'s premium build environment more accessible to those who are still evaluating whether nixpkgs gold :tm: is the answer to their software building needs. We could offer a free tier with limited access to premium features, then either make it a limited trial or support it with ads injected via pre-phase hooks. To ensure that the ads aren't drowned out by other build logs, we could need to add `sleep` calls, which would also incentivize the user to upgrade to nixpkgs gold :tm:.

**Comment by numinit** [comment]
Will Hydra need a nixpkgs gold™ license?

**Comment by Jaculabilis** [comment]
That depends. In the future, we may build premium derivations on hydra gold :tm: and allocate a license there instead.

**Comment by Jaculabilis** [comment]
A free trial tier supported by ads is now available whenever no nixpkgs gold :tm: license is detected.
